### ISSUE TITLE
Keyword only allows existing Albums

### ISSUE THREAD

**Issue by amballin** [mrworf/photoframe#55]
I have forced an update to get the most recent changes, clearly you have spent a great deal of time improving photoframe - Thank you.

It appears that the keywords now only accept album names that match the name (spelling, not case)of an existing album.  In the prior version, with Picasa, any search word was possible.  When there is no match the UI (browser) hangs until I do a refresh - which basically removes the entered search value and then the preview and the actual display show message indicating no albums were specified.

Logs:
~/photoframe# ./frame.py --debug
2019-01-08 09:24:16,662 - DEBUG - Found "/boot/http-auth.json", loading the data
2019-01-08 09:24:16,726 - DEBUG - Internal display: {'3d_modes': [], 'width': 8, 'rate': 60, 'code': 1, 'mode': 'INTERNAL', 'scan': '(internal)', 'aspect_ratio': '', 'reverse': True, 'depth': 16, 'height': 8}
2019-01-08 09:24:17,872 - INFO - ColorSensor not available
2019-01-08 09:24:17,875 - DEBUG - hourOn = 4, hourOff = 22
2019-01-08 09:24:17,876 - DEBUG - Powermode changed to 'none'
2019-01-08 09:24:32,417 - INFO - Starting presentation
2019-01-08 09:24:49,262 - DEBUG - Query Google Photos for album named "yellow"
2019-01-08 09:24:49,268 - DEBUG - Invoking 0 protected resource request hooks.
2019-01-08 09:24:49,270 - DEBUG - Adding token {u'access_token': u'xxxx', u'expires_in': 3600, u'expires_at': 1546958244.58698, u'token_type': u'Bearer', u'scope': [u'https://www.googleapis.com/auth/photoslibrary.readonly'], u'refresh_token': u'yyyy'} to request.
2019-01-08 09:24:49,271 - DEBUG - Requesting url https://photoslibrary.googleapis.com/v1/albums using method GET.
2019-01-08 09:24:49,272 - DEBUG - Supplying headers {u'Authorization': u'xxxxx'} and data None
2019-01-08 09:24:49,273 - DEBUG - Passing through key word arguments {'allow_redirects': True, 'params': {'pageSize': 50}, 'stream': False}.
2019-01-08 09:24:49,311 - DEBUG - Starting new HTTPS connection (1): photoslibrary.googleapis.com
2019-01-08 09:24:50,258 - DEBUG - https://photoslibrary.googleapis.com:443 "GET /v1/albums?pageSize=50 HTTP/1.1" 200 None
2019-01-08 09:24:50,287 - DEBUG - Album: Fireworks
2019-01-08 09:24:50,288 - DEBUG - Album: Utah
2019-01-08 09:24:50,288 - DEBUG - Album: SingleShot
2019-01-08 09:24:50,289 - DEBUG - Album: Vail Gold Club 
2019-01-08 09:24:50,290 - DEBUG - Album: Vail 2010
2019-01-08 09:24:50,293 - DEBUG - Invoking 0 protected resource request hooks.
2019-01-08 09:24:50,294 - DEBUG - Adding token {u'access_token': u'xxxxxx', u'expires_in': 3600, u'expires_at': 1546958244.58698, u'token_type': u'Bearer', u'scope': [u'https://www.googleapis.com/auth/photoslibrary.readonly'], u'refresh_token': u'yyyyy'} to request.
2019-01-08 09:24:50,295 - DEBUG - Requesting url https://photoslibrary.googleapis.com/v1/sharedAlbums using method GET.
2019-01-08 09:24:50,296 - DEBUG - Supplying headers {u'Authorization': u'xxxx'} and data None
2019-01-08 09:24:50,297 - DEBUG - Passing through key word arguments {'allow_redirects': True, 'params': {'pageSize': 50}, 'stream': False}.
2019-01-08 09:24:50,307 - DEBUG - Starting new HTTPS connection (1): photoslibrary.googleapis.com
2019-01-08 09:24:50,878 - DEBUG - https://photoslibrary.googleapis.com:443 "GET /v1/sharedAlbums?pageSize=50 HTTP/1.1" 200 None

Note the search for "yellow" on the googlephotos webpage does show a few pictures.

Hopefully search using any keyword can be repaired. The ability to find a person across all albums is a nice feature

**Comment by mrworf** [comment]
The issue with keyword search not working is a Google limitation. The new api simply doesn't support arbitrary keywords. The old api is no longer supported and will stop functioning by March at the latest. 

It shouldn't hang though if the album doesn't exists. Do you run adblock or ublock (or similar)? They could interfere with the Javascript (but I haven't heard of a case like that yet) 

⁣Sent from TypeApp ​

**Comment by amballin** [comment]
Thanks for the explanation,  to answer your question: to the best of my knowledge I do not have adblockers running,  I get the same hang condition on Safari, Chrome on MacOS Mojave,  and also on iOS.   The hang condition occurs when searching for a nonexistent album.  I have tested without any albums specified and also with one named to match an existing album - both end up with the same hang result.

**Comment by mrworf** [comment]
Any chance this issue has been resolved with the latest updates? If not, could you pull up the javascript console for the browser and try. If there is a bug in the scripts, it should show there.

**Comment by amballin** [comment]
i’ll check into it and let you know, have been heads-down on something else

**Comment by mrworf** [comment]
No worries, me too :) take your time, I just didn't want this one to fall between the chairs and be forgotten

**Comment by amballin** [comment]
Hi,

I forced an update and now I do not get anything displayed in the preview window nor do I get anything on the display.   This is separate from the original issue.

I was able to test the query from the browser,   it still hangs when asking for search terms that do not match an album name.

Below is what I could find in the Java script Console,  I am not sure what to look for, if you need more specific information I would gladly gather that for you, but I would need guidance.

Thanks, Andy




Java Console:
Failed to load resource: the server responded with a status of 500 (INTERNAL SERVER ERROR)

 <html><head><title>Internal error</title></head><body style="font-family: Verdana"><h1>Uh oh, something went wrong...</h1>
    Please go to <a href="https://github.com/mrworf/photoframe/issues">github</a>
    and see if this is a known issue, if not, feel free to file a <a href="https://github.com/mrworf/photoframe/issues/new">new issue<a> with the
    following information:
    <pre style="margin: 15pt; padding: 10pt; border: 1px solid; background-color: #eeeeee">Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/dist-packages/flask_httpauth.py", line 93, in decorated
    return f(*args, **kwargs)
  File "./frame.py", line 294, in cfg_keywords
    result = services.addServiceKeywords(service, request.json['keywords'])
  File "/root/photoframe/modules/servicemanager.py", line 187, in addServiceKeywords
    return svc.addKeywords(keywords)
  File "/root/photoframe/services/svc_googlephotos.py", line 134, in addKeywords
    result = BaseService.addKeywords(self, keywords)
  File "/root/photoframe/services/base.py", line 256, in addKeywords
    tst = self.validateKeywords(keywords)
  File "/root/photoframe/services/svc_googlephotos.py", line 127, in validateKeywords
    albumId = self.translateKeywordToId(keywords)
  File "/root/photoframe/services/svc_googlephotos.py", line 295, in translateKeywordToId
    for i in range(len(data['sharedAlbums'])):
KeyError: 'sharedAlbums'
</pre>
    Thank you for your patience
    </body>
    </html>


Headers:
Summary
URL: http://192.168.1.36:7777/keywords/10074187f97e866e55c4889262828dcf2331528f/add
Status: 500 INTERNAL SERVER ERROR
Source: Network
Address: 192.168.1.36:7777

Request
POST /keywords/10074187f97e866e55c4889262828dcf2331528f/add HTTP/1.1
Content-Type: application/json; charset=UTF-8
Accept: application/json, text/javascript, */*; q=0.01
Authorization: Basic YmFsbGluOndpbmRzb25n
Host: 192.168.1.36:7777
Accept-Language: en-us
Accept-Encoding: gzip, deflate
Origin: http://192.168.1.36:7777
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.2 Safari/605.1.15
Connection: keep-alive
Referer: http://192.168.1.36:7777/
Content-Length: 21
X-Requested-With: XMLHttpRequest

Response
HTTP/1.1 500 INTERNAL SERVER ERROR
Content-Type: text/html; charset=utf-8
Pragma: no-cache
Date: Wed, 23 Jan 2019 23:22:24 GMT
Content-Length: 1752
Cache-Control: public, max-age=0
Expires: 0
Server: Werkzeug/0.11.15 Python/2.7.13

Request Data
MIME Type: application/json
Encoding: UTF-8
Request Data: 


The request data shows the string I tried to add.


   Clicking on the link next to the 500 error yields a browser page:
Not Found

The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.



Note that I did use the same term on google photos and it returned a few pictures.

**Comment by mrworf** [comment]
Could it be that you don't have any shared albums? 

Because that's why it's failing. The code wrongly assumes that all users have shared albums, and it seems that if you don't have any, then google doesn't even return zero, it just omits the information entirely.

**Comment by amballin** [comment]
Okay,  I did not have any shared albums….   so I created and shared a test album.   Now the system does not hang when I enter a search term (ie yellow) but it returns telling me there is no album by that name.  any album that exists does get added to the list.

However,  I am not seeing anything on the TV nor in the preview window.

**Comment by mrworf** [comment]
The preview window is simply framegrabbing what the TV shows. Can you share what /debug says? Should have some useful information now

**Comment by amballin** [comment]
After creating the shared album  I then pressed the reboot (photo frame browser) and I could see messages on TV.   Once it restarted it seems to be working again.   I doubt it is related, more likely sun spots :-)

Do you know if Google will eventually support the search capability that picassa had?

Thanks for patience and guidance.

Andy

**Comment by mrworf** [comment]
They support some stuff but not the freeform of picasa. My intention is to add some of it as special params for the new services, so you can do stuff like:
```
album:someAlbum landscape:yes people:no
```
But its's a bit into the future currently

**Comment by amballin** [comment]
Awesome.  Thanks for all your efforts

**Comment by mrworf** [comment]
Added a fix for users without shared albums. Should no longer crash. Next update will add this.
